# Generated by Django 5.1.2 on 2024-10-22 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0003_alter_tasklist_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasklist',
            options={'ordering': ['id']},
        ),
    ]
